---
# defaults file for freeradius-eduroam

# Everything below should be overridden, and are here merely to make
# sure we have something to work with when the templating engine runs
eduroam_flr_servers:
  - hostname: flr-cpt.eduroam.ac.za
    ip: 155.232.195.20
    port: 1812
    secret: MySharedSecret
  - hostname: flr-jnb.eduroam.ac.za
    ip: 155.232.195.21
    port: 1812
    secret: MySharedSecret
radius_realm: example.ac.za
radius_local_users:
  - username: nren_radius_test
    password: PleaseChangeThisPassword

use_pam: no
pam_service_name: radiusd

use_ldap: no
ldap_is_edir: no
ldap_servers:
  - hostname: localhost
    port: 389
    base_dn: dc=example,dc=org
    start_tls: yes

send_cui: yes
send_username: no
